### ISSUE TITLE
how much RAM does it need to run? 

### ISSUE THREAD

**Issue by cliffnyang** [openeventdata/mordecai#14]
I ran into a memory issue. it says it needs 10G RAM? is this expected? i have 16G RAM machine.

<img width="1280" alt="screen shot 2016-07-26 at 11 00 02 pm" src="https://cloud.githubusercontent.com/assets/12943567/17165362/bdabf91e-5384-11e6-9585-aeb671e60ce1.png">

**Comment by ahalterman** [comment]
To maximize performance, the Java heap size for `es-geonames` is set to be very large on the `es-geonames` image, since we're usually running it on a separate machine or on a machine with 64+ gigs. The geonames index is about 6 gigs, word2vec is 2-3 I think, and MITIE is maybe one. When I redo the `es-geonames` Dockerfile (see issue #11), you'll be able to change the heap size to something smaller when you build.
