### ISSUE TITLE
Add Spanish /country and /places

### ISSUE THREAD

**Issue by ahalterman** [openeventdata/mordecai#15]
Part of the design of Mordecai is to accommodate non-English languages with a minimum of modification and training.

MITIE already has a pre-made Spanish NER model, so all we need for a Spanish-language Mordecai is Spanish word2vec. 
- [ ] /country
- [ ] /places

**Comment by chilland** [comment]
#19 should make this much easier as the images no longer need to be rebuilt to support new models.

**Comment by ahalterman** [comment]
- [ ] Did the Spanish bigram model work?
- [ ] Retrain Spanish word2vec with Gigaword, not just Wikipedia

**Comment by ahalterman** [comment]
Handle this using spacy models instead. Moving discussion to #25.

**Comment by PTB-OEDA** [comment]
FYI..... Affects our Spanish test.

On Oct 15, 2017 19:46, "Andy Halterman" <notifications@github.com> wrote:

Handle this using spacy models instead. Moving discussion to #25
<https://github.com/openeventdata/mordecai/issues/25>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/openeventdata/mordecai/issues/15#issuecomment-336754579>,
or mute the thread
