### ISSUE TITLE
ImportError: dlopen: cannot load any more object with static TLS , while using mordecai

### ISSUE THREAD

**Issue by kgaswin93** [openeventdata/mordecai#61]
Hi,
       I'm trying to perform geoparsing in several servers, all but one server fails to run mordecai, attached stack trace. All servers are identical with only difference being - mongodb is also run in the same server where mordecai won't run. I tried changing import orders but couldn't get far with solving it. Please let me know about your inputs and how should i proceed.
[stacktrace.txt](https://github.com/openeventdata/mordecai/files/2446983/stacktrace.txt)

Regards,
Aswin

**Comment by ahalterman** [comment]
Yeah, it looks like a Tensorflow issue, perhaps in combination with spaCy ([thread])(https://github.com/tensorflow/models/issues/523). I think that it's happening on the Mongo server is not a coincidence. I usually give Mongo its own server in big distributed tasks like this one. And since Mongo/Java also uses thread local storage, it could be that that's what's causing the resource to be used up.
